/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollegeFile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'fileName' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'fileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCollegeFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCollegeFile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getCollegeFile' : IDL.Func([IDL.Text], [IDL.Opt(CollegeFile)], ['query']),
  'listCollegeFiles' : IDL.Func([], [IDL.Vec(CollegeFile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollegeFile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'fileName' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'fileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addCollegeFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCollegeFile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getCollegeFile' : IDL.Func([IDL.Text], [IDL.Opt(CollegeFile)], ['query']),
    'listCollegeFiles' : IDL.Func([], [IDL.Vec(CollegeFile)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };